### ISSUE TITLE
AC - aard daghosp -aferese (e617)

### ISSUE THREAD

**Issue by PieterMaertens** [uz-leuven/progress.vbhc-dashboard#10]
Dag Wouter,
Was nog een test aan het doen en heb het gevoel dat er een verdubbeling is voor FM Aferese:
![image](https://user-images.githubusercontent.com/40758761/125091623-de294c80-e0d0-11eb-9fb3-62556b32268b.png)
Groeten, Pieter

**Comment by WouterDH-UZL** [comment]
Dag Pieter,

Bedankt voor alle tests. Straf dat je dit nog gevonden hebt, was een bug specifiek voor één AC. 

De oorzaak van de bug lag bij een fout in één van de ACZP-tabellen. Ik heb nu een testthat-statement geschreven in mijn code zodat ik zulke problemen makkelijker ontdek.

Vriendelijke groeten,

Wouter
