### ISSUE TITLE
MD - Financieel - Overzicht

### ISSUE THREAD

**Issue by PieterMaertens** [uz-leuven/progress.vbhc-dashboard#8]
Dag Wouter,
Ik heb het gevoel dat niet steeds alle "subcategoriën" getoond worden in het overzicht:
Bijvoorbeeld: endocrinologie
![image](https://user-images.githubusercontent.com/40758761/124910699-291d6400-dfec-11eb-832c-84cb2d9cbf57.png)
Naast Honoraria, conventies en rest, verwacht ik ook dagforfaits (of vallen die onder rest?)
Zou sowieso de kleuren proberen constant te houden over de MD's heen voor de subcategoriën.
Groeten,
Pieter

**Comment by WouterDH-UZL** [comment]
Dag Pieter, 
De restgroep zou alleen berekend mogen worden wanneer je de figuur opdeelt per afdeling, dat was dus een bug. Dit zou nu gecorrigeerd moeten zijn.
De legende werd ook verbeterd.
Groeten,
Wouter

**Comment by PieterMaertens** [comment]
Dag Wouter,
De bug is opgelost en ook de legende is stabiel. Ik heb nog 1 bijkomende vraag: is er een reden waarom LVZ niet voorkomt in het overzicht?
Groeten,
Pieter

**Comment by WouterDH-UZL** [comment]
Dag Pieter,

LVZ wordt inbegrepen onder honoraria. Zie ook de categorie 'HON LVZ':

![image](https://user-images.githubusercontent.com/72191523/125039895-4c511d80-e097-11eb-8df3-c5581a54a981.png)

De selectie 'Laagvariabele zorg (Detail)' zoomt gewoon in op 'HON LVZ'.

Vriendelijke groeten,

Wouter

**Comment by PieterMaertens** [comment]
Ok super, was niet helemaal mee.
