### ISSUE TITLE
Vaste pagina hoogte veroorzaakt een scroll bar

### ISSUE THREAD

**Issue by PieterMaertens** [uz-leuven/progress.vbhc-dashboard#9]
Dag Wouter,
Is er iets gewijzigd aan de wijze waarop de pagina word gegenereerd?
Ik krijg namelijk in een aantal gevallen een scrollbar rechts terwijl ik nog heel wat witruimte heb onderaan de pagina.
![image](https://user-images.githubusercontent.com/40758761/125030006-bf07cc00-e08a-11eb-8032-e8f3eb469cac.png)
Ik bekijk de app via Microsoft Edge.
Groeten,
Pieter

**Comment by WouterDH-UZL** [comment]
Dag Pieter,

Weer je sinds wanneer dit zo is? Ik merk dat de productieserver het ook heeft en daar heb ik al een tijd niets meer aan aangepast. Het valt ook harder op op grotere schermen.

Vriendelijke groeten,

Wouter

**Comment by PieterMaertens** [comment]
Geen idee, is de eerste keer dat het mij opvalt.
Groeten, Pieter

**Comment by WouterDH-UZL** [comment]
Dag Pieter,

Dit zou nu terug in orde moeten zijn.

Vriendelijke groeten,

Wouter
